In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.svm import SVR
from sklearn.metrics import r2_score,accuracy_score
from sklearn import datasets

In [4]:
df = datasets.load_diabetes(as_frame=True).frame

In [5]:
df.shape

(442, 11)

In [6]:
df.isnull().sum()

age       0
sex       0
bmi       0
bp        0
s1        0
s2        0
s3        0
s4        0
s5        0
s6        0
target    0
dtype: int64

In [7]:
df.sample(10)

          age       sex       bmi  ...        s5        s6  target
364  0.001751  0.050680 -0.006206  ...  0.014821  0.098333   262.0
21  -0.085430  0.050680 -0.022373  ... -0.072133 -0.017646    49.0
293 -0.070900 -0.044642  0.092953  ... -0.054540 -0.001078   200.0
382  0.048974 -0.044642  0.060618  ...  0.104136  0.036201   132.0
238  0.034443  0.050680 -0.009439  ...  0.011011 -0.021788   257.0
374 -0.107226 -0.044642 -0.034229  ... -0.000612 -0.079778   140.0
42  -0.060003  0.050680 -0.010517  ... -0.009919 -0.034215    61.0
66  -0.009147  0.050680 -0.018062  ...  0.000272  0.019633   150.0
368 -0.016412  0.050680  0.002417  ...  0.085531  0.081764   123.0
340 -0.016412 -0.044642 -0.013751  ... -0.035816 -0.030072   216.0

[10 rows x 11 columns]

In [8]:
x = df.drop("target",axis=1)
y = df["target"]

In [9]:
x

          age       sex       bmi  ...        s4        s5        s6
0    0.038076  0.050680  0.061696  ... -0.002592  0.019907 -0.017646
1   -0.001882 -0.044642 -0.051474  ... -0.039493 -0.068332 -0.092204
2    0.085299  0.050680  0.044451  ... -0.002592  0.002861 -0.025930
3   -0.089063 -0.044642 -0.011595  ...  0.034309  0.022688 -0.009362
4    0.005383 -0.044642 -0.036385  ... -0.002592 -0.031988 -0.046641
..        ...       ...       ...  ...       ...       ...       ...
437  0.041708  0.050680  0.019662  ... -0.002592  0.031193  0.007207
438 -0.005515  0.050680 -0.015906  ...  0.034309 -0.018114  0.044485
439  0.041708  0.050680 -0.015906  ... -0.011080 -0.046883  0.015491
440 -0.045472 -0.044642  0.039062  ...  0.026560  0.044529 -0.025930
441 -0.045472 -0.044642 -0.073030  ... -0.039493 -0.004222  0.003064

[442 rows x 10 columns]

In [10]:
y

0      151.0
1       75.0
2      141.0
3      206.0
4      135.0
       ...
437    178.0
438    104.0
439    132.0
440    220.0
441     57.0
Name: target, Length: 442, dtype: float64

In [11]:
from sklearn.preprocessing import StandardScaler
sclr = StandardScaler()

y = sclr.fit_transform(y.values.reshape(-1,1)).ravel()

In [17]:
x_train,x_test,y_train,y_test = train_test_split(
    x,y,random_state=42,test_size=0.3
)

In [18]:
svr = SVR()

svr.fit(x_train,y_train)
y_pred = svr.predict(x_test)

r2 = r2_score(y_test,y_pred)
print("r2_score : ", r2)

r2_score :  0.48943128840368344

In [20]:
param_grid = {
    "C": [1, 5, 10,30,50,70,100],
    "kernel": ["rbf", "linear","poly","sigmoid"],
    "epsilon": [0.01, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6,]
}

grid_seacrh=GridSearchCV(svr,param_grid,scoring="r2",cv=5)

grid_seacrh.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=SVR(),
             param_grid={'C': [1, 5, 10, 30, 50, 70, 100],
                         'epsilon': [0.01, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6],
                         'kernel': ['rbf', 'linear', 'poly', 'sigmoid']},
             scoring='r2')

In [21]:
print("best parameter :",grid_seacrh.best_params_)

best parameter : {'C': 10, 'epsilon': 0.1, 'kernel': 'linear'}

In [23]:
best_model = SVR(C=10,kernel="linear",epsilon=0.1)

best_model.fit(x_train,y_train)
y_pred_train = best_model.predict(x_train)
y_pred = best_model.predict(x_test)

print("best r2_score(train) : ",r2_score(y_train,y_pred_train))
print("best r2_score(test) : ",r2_score(y_test,y_pred))

best r2_score(train) :  0.514473254728114
best r2_score(test) :  0.47482725122988534