In [2]:
import requests

In [3]:
url = "https://stephen-king-api.onrender.com/api/books"
res = requests.get(url)

In [4]:
res

In [5]:
j_data = res.json()

In [8]:
import pandas as pd 
df = pd.json_normalize(j_data["data"])

In [9]:
df

,id,Year,Title,handle,Publisher,ISBN,Pages,Notes,created_at,villains
0,1,1974,Carrie,carrie,Doubleday,978-0-385-08695-0,199,[],2023-11-13T23:48:47.848Z,"[{'name': 'Tina Blake', 'url': 'https://stephe..."
1,2,1975,Salem's Lot,salem-s-lot,Doubleday,978-0-385-00751-1,439,"[Nominee, World Fantasy Award, 1976[2]]",2023-11-13T23:48:48.098Z,"[{'name': 'Kurt Barlow', 'url': 'https://steph..."
2,3,1977,The Shining,the-shining,Doubleday,978-0-385-12167-5,447,"[Runner-up (4th place), Locus Award for Best F...",2023-11-13T23:48:48.219Z,"[{'name': 'Horace M. Derwent', 'url': 'https:/..."
3,4,1977,Rage,rage,Signet Books,978-0-451-07645-8,211,[Published under pseudonym Richard Bachman],2023-11-13T23:48:48.339Z,[]
4,5,1978,The Stand,the-stand,Doubleday,978-0-385-12168-2,823,"[Nominee, World Fantasy Award, 1979, Runner-up...",2023-11-13T23:48:48.477Z,"[{'name': 'Donald Merwin Elbert', 'url': 'http..."
...,...,...,...,...,...,...,...,...,...,...
58,59,2018,The Outsider,the-outsider,Scribner,978-1-50118-098-9,576,"[First novel in the Holly Gibney Series, Runne...",2023-11-13T23:48:55.165Z,"[{'name': 'The Outsider (Creature)', 'url': 'h..."
59,60,2018,Elevation,elevation,Scribner,978-1-98210-231-9,144,[],2023-11-13T23:48:55.291Z,[]
60,61,2019,The Institute,the-institute,Scribner,978-1-98211-056-7,576,"[Nominee, British Fantasy Award's August Derle...",2023-11-13T23:48:55.457Z,"[{'name': 'Gladys Hickson', 'url': 'https://st..."
61,62,2021,Later,later,Hard Case Crime,978-1-78909-649-1,256,[],2023-11-13T23:48:55.579Z,[]
62,63,2021,Billy Summers,billy-summers,Scribner,978-1-982-17361-6,528,[],2023-11-13T23:48:55.753Z,[]

In [10]:
df.columns

Index(['id', 'Year', 'Title', 'handle', 'Publisher', 'ISBN', 'Pages', 'Notes',
       'created_at', 'villains'],
      dtype='object')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          63 non-null     int64
 1   Year        63 non-null     int64
 2   Title       63 non-null     object
 3   handle      63 non-null     object
 4   Publisher   63 non-null     object
 5   ISBN        63 non-null     object
 6   Pages       63 non-null     int64
 7   Notes       63 non-null     object
 8   created_at  63 non-null     object
 9   villains    63 non-null     object
dtypes: int64(3), object(7)
memory usage: 5.1+ KB

In [12]:
df = df [['id','Year','Title','handle']]

In [13]:
df

    id  Year          Title         handle
0    1  1974         Carrie         carrie
1    2  1975    Salem's Lot    salem-s-lot
2    3  1977    The Shining    the-shining
3    4  1977           Rage           rage
4    5  1978      The Stand      the-stand
..  ..   ...            ...            ...
58  59  2018   The Outsider   the-outsider
59  60  2018      Elevation      elevation
60  61  2019  The Institute  the-institute
61  62  2021          Later          later
62  63  2021  Billy Summers  billy-summers

[63 rows x 4 columns]