In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import r2_score,accuracy_score,mean_squared_error,precision_score

In [ ]:
dataset = pd.read_csv("shop_smart_ecommerce.csv")
dataset.shape

(2240, 22)

In [5]:
dataset.sample(15)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Complain,Response
761,6887,1967,Graduation,Single,79146.0,1,1,24-04-2014,33,245,...,21,43,16,2,8,1,8,6,0,0
1535,9771,1988,2n Cycle,Single,23331.0,1,0,05-10-2012,97,104,...,24,15,5,6,5,1,5,9,0,0
1485,9988,1976,Master,Single,70379.0,0,1,03-03-2013,84,553,...,65,67,8,3,6,3,13,4,0,0
2224,4286,1970,PhD,Single,57642.0,0,1,09-01-2014,24,580,...,8,0,27,3,7,6,6,4,0,0
1503,3594,1973,Master,Married,54108.0,1,1,05-11-2012,74,539,...,8,6,97,13,8,2,9,8,0,0
1137,8015,1962,PhD,Divorced,85696.0,0,0,03-05-2013,88,714,...,116,0,12,1,4,6,9,1,0,1
1034,1020,1973,Graduation,Married,79593.0,0,0,12-05-2014,70,350,...,110,133,145,1,5,6,7,2,0,0
1943,10413,1984,Graduation,Married,72570.0,0,0,25-04-2014,67,274,...,151,141,224,1,4,6,12,1,0,0
695,9239,1961,Master,Married,61923.0,0,2,26-07-2013,94,92,...,3,3,6,1,2,1,4,3,0,0
891,7108,1965,Master,Widow,51390.0,1,1,08-09-2012,54,205,...,23,2,56,6,5,2,5,5,0,0
2225,4749,1968,Graduation,Together,58554.0,1,1,26-09-2012,55,368,...,38,0,88,6,8,2,6,7,0,0
1385,10909,1948,Graduation,Married,92344.0,0,0,15-01-2014,9,992,...,51,19,119,0,5,10,5,1,0,0
952,5320,1973,Master,Divorced,44051.0,1,1,29-01-2013,20,79,...,6,3,18,4,3,1,4,6,0,1
1476,217,1956,Master,Single,64857.0,0,0,23-11-2012,78,556,...,210,0,43,1,7,5,10,4,0,0
2020,9829,1978,Graduation,Together,28587.0,1,0,12-02-2014,42,22,...,12,10,13,3,2,0,4,6,0,0

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   object
 3   Marital_Status       2240 non-null   object
 4   Income               2216 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   object
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntGoldProds         2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  Complain             2240 non-null   int64
 21  Response             2240 non-null   int64
dtypes: float64(1), int64(18), object(3)
memory usage: 385.1+ KB

In [7]:
dataset.describe

<bound method NDFrame.describe of          ID  Year_Birth   Education Marital_Status   Income  Kidhome  \
0      5524        1957  Graduation         Single  58138.0        0
1      2174        1954  Graduation         Single  46344.0        1
2      4141        1965  Graduation       Together  71613.0        0
3      6182        1984  Graduation       Together  26646.0        1
4      5324        1981         PhD        Married  58293.0        1
...     ...         ...         ...            ...      ...      ...
2235  10870        1967  Graduation        Married  61223.0        0
2236   4001        1946         PhD       Together  64014.0        2
2237   7270        1981  Graduation       Divorced  56981.0        0
2238   8235        1956      Master       Together  69245.0        0
2239   9405        1954         PhD        Married  52869.0        1

      Teenhome Dt_Customer  Recency  MntWines  ...  MntFishProducts  \
0            0  04-09-2012       58       635  ...              172
1            1  08-03-2014       38        11  ...                2
2            0  21-08-2013       26       426  ...              111
3            0  10-02-2014       26        11  ...               10
4            0  19-01-2014       94       173  ...               46
...        ...         ...      ...       ...  ...              ...
2235         1  13-06-2013       46       709  ...               42
2236         1  10-06-2014       56       406  ...                0
2237         0  25-01-2014       91       908  ...               32
2238         1  24-01-2014        8       428  ...               80
2239         1  15-10-2012       40        84  ...                2

      MntSweetProducts  MntGoldProds  NumDealsPurchases  NumWebPurchases  \
0                   88            88                  3                8
1                    1             6                  2                1
2                   21            42                  1                8
3                    3             5                  2                2
4                   27            15                  5                5
...                ...           ...                ...              ...
2235               118           247                  2                9
2236                 0             8                  7                8
2237                12            24                  1                2
2238                30            61                  2                6
2239                 1            21                  3                3

      NumCatalogPurchases  NumStorePurchases  NumWebVisitsMonth  Complain  \
0                      10                  4                  7         0
1                       1                  2                  5         0
2                       2                 10                  4         0
3                       0                  4                  6         0
4                       3                  6                  5         0
...                   ...                ...                ...       ...
2235                    3                  4                  5         0
2236                    2                  5                  7         0
2237                    3                 13                  6         0
2238                    5                 10                  3         0
2239                    1                  4                  7         0

      Response
0            1
1            0
2            0
3            0
4            0
...        ...
2235         0
2236         0
2237         0
2238         0
2239         1

[2240 rows x 22 columns]>

In [8]:
dataset.columns

Index(['ID', 'Year_Birth', 'Education', 'Marital_Status', 'Income', 'Kidhome',
       'Teenhome', 'Dt_Customer', 'Recency', 'MntWines', 'MntFruits',
       'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts',
       'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases',
       'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth',
       'Complain', 'Response'],
      dtype='object')

In [9]:
dataset

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Complain,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,172,88,88,3,8,10,4,7,0,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,2,1,6,2,1,1,2,5,0,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,111,21,42,1,8,2,10,4,0,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,10,3,5,2,2,0,4,6,0,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,46,27,15,5,5,3,6,5,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10870,1967,Graduation,Married,61223.0,0,1,13-06-2013,46,709,...,42,118,247,2,9,3,4,5,0,0
2236,4001,1946,PhD,Together,64014.0,2,1,10-06-2014,56,406,...,0,0,8,7,8,2,5,7,0,0
2237,7270,1981,Graduation,Divorced,56981.0,0,0,25-01-2014,91,908,...,32,12,24,1,2,3,13,6,0,0
2238,8235,1956,Master,Together,69245.0,0,1,24-01-2014,8,428,...,80,30,61,2,6,5,10,3,0,0
2239,9405,1954,PhD,Married,52869.0,1,1,15-10-2012,40,84,...,2,1,21,3,3,1,4,7,0,1

In [10]:
print(dataset["Revenue"].value_counts().unique)

KeyError: 'Revenue'

In [ ]:
counts = dataset["Revenue"].value_counts()

In [ ]:
print(counts)

In [11]:
true_count = dataset["Revenue"].sum()
false_count = len(dataset) - true_count

plt.pie([true_count, false_count],
        labels=["True", "False"],
        autopct='%1.1f%%')

plt.title("True vs False Distribution")
plt.show()

KeyError: 'Revenue'

In [ ]:
sns.countplot(x="Weekend", hue="Revenue", data=dataset)
plt.show()

In [ ]:
sns.histplot(dataset["ProductRelated_Duration"])

In [ ]:
dataset["ProductRelated_Duration"].sample(10)

In [ ]:
dataset.groupby("Weekend")["Revenue"].mean()

In [ ]:
sns.boxplot(x="Revenue", y="ProductRelated_Duration", data=dataset)

In [ ]:
sns.boxplot(dataset["Administrative_Duration"])

In [ ]:
dataset.groupby("Month")["Revenue"].mean()

In [ ]:
for i in dataset.columns:
    sns.countplot(
    x=i,hue="Revenue",
    data=dataset
    )
    plt.show()

In [ ]:

corr = dataset.corr(numeric_only=True)
plt.figure(figsize=(12,8))
sns.heatmap(corr, annot=True, cmap="coolwarm")
plt.tight_layout
plt.show()

In [ ]:
sns.countplot(x="VisitorType", hue="Revenue", data=dataset)

In [ ]:
dataset["Weekend"] = dataset["Weekend"].astype(int)
dataset["Revenue"] = dataset["Revenue"].astype(int)

In [ ]:
dataset.info()

In [ ]:
dataset["Revenue"] = dataset["Revenue"].astype(int)

In [ ]:
dataset["Revenue"].value_counts().unique()

In [ ]:
X = dataset.drop("Revenue", axis=1)
y = dataset["Revenue"]

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report,accuracy_score,r2_score

In [ ]:
from sklearn.pipeline import Pipeline

categorical_pipeline = Pipeline([
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

In [ ]:
categorical_features = [
    'Month','VisitorType'
]

In [ ]:
from sklearn.compose import ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ("cat", categorical_pipeline, categorical_features)
    ]
)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
param_grid = {

"max_depth" : [3,5,7,9,11,13,15],
"min_samples_split": [2,5,10,15,20,13,9],

}

grid = GridSearchCV(
    model,
    param_grid,
    cv= 5,
    n_jobs=-1
)
 
grid.fit(X_train,y_train)

print(grid.best_params_)

{'max_depth': 3, 'min_samples_split': 2}

In [ ]:
model = DecisionTreeClassifier(max_depth=3,min_samples_split=2)
model.fit(X_train,y_train)

y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

print("classification train report : ",classification_report(y_train_pred,y_train))
print("classification test report : ",classification_report(y_test_pred,y_test))

print("accuracy score train report : ",accuracy_score(y_train_pred,y_train))
print("accuracy score test report : ",accuracy_score(y_test_pred,y_test))

classification train report :                precision    recall  f1-score   support

           0       1.00      0.85      0.92      9864
           1       0.00      0.00      0.00         0

    accuracy                           0.85      9864
   macro avg       0.50      0.42      0.46      9864
weighted avg       1.00      0.85      0.92      9864

classification test report :                precision    recall  f1-score   support

           0       1.00      0.83      0.91      2466
           1       0.00      0.00      0.00         0

    accuracy                           0.83      2466
   macro avg       0.50      0.42      0.45      2466
weighted avg       1.00      0.83      0.91      2466

accuracy score train report :  0.8482360097323601
accuracy score test report :  0.8333333333333334

c:\Users\jinju\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\jinju\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\jinju\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\jinju\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\jinju\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\jinju\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
ref = RandomForestClassifier()

params = {
    "n_estimators":[100,201,301,401,501,601],
    "max_depth":[3,5,10,15,20,25],
    "min_samples_split":[2,3,5,7,9,13]
}

grid = GridSearchCV(
    ref,
    params,
    cv=5,
    n_jobs= -1
    )

grid.fit(X_train,y_train)
print("estimator",grid.best_estimator_,"best_params_",grid.best_params_,"best_score_",grid.best_score_)

estimator RandomForestClassifier(max_depth=3) best_params_ {'max_depth': 3, 'min_samples_split': 2, 'n_estimators': 100} best_score_ 0.848236024052909

In [ ]:
ref = RandomForestClassifier(max_depth=6,min_samples_split=3,n_estimators=101 )

ref.fit(X_train,y_train)

y_train_pred = ref.predict(X_train)
y_test_pred = ref.predict(X_test)

print("accuracy score train report : ",accuracy_score(y_train_pred,y_train))
print("accuracy score test report : ",accuracy_score(y_test_pred,y_test))

accuracy score train report :  0.8482360097323601
accuracy score test report :  0.8333333333333334